language: c

script:
- unset JRUBY_OPTS
- test -f ~/.rvmrc && cat ~/.rvmrc || true
- ./build.sh

cache: ccache

matrix:
  include:
  - os: osx
    before_install:
      - sw_vers
    install:
      - unset -f pushd
      - unset -f popd
    osx_image: xcode10.2-rubies
    cache: &osx_cache
      ccache: true
      directories:
        - /usr/local/Cellar/python
        - /usr/local/opt/python

before_cache:
  - echo rvm_auto_reload_flag=1 >> ~/.rvmrc

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

notifications:
  email: false
